# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bff2ba522a64e876b6b52e8dc545a1522cae49790b5da02688ee4e5ec5d8013a347827ad7da8c58e45705176336506277383beb153ceb80d175dc656b502d9db

test:
  secret_key_base: 4c09f09311f6f957f3ac6a7a1b30c29fa58174bf6dd0ec52f5a012c7db1d8d3c466df7ebcdb26e8ec394c92d5a1bf1227deaf5660d19300c8646d4d24e09b5cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
